apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eventarz-application
  name: eventarz-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventarz-application
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eventarz-application
    spec:
      containers:
        - image: eventarzcontainerregistry.azurecr.io/eventarz-application:latest
          name: eventarz-application
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eventarz-application
  name: eventarz-application
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: eventarz-application
  type: ClusterIP
